services:
  db-service:
    container_name: postgres-16
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  wbt-customer-api:
    container_name: wbt-customer
    image: greengorilla/wbt-customer-api:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-service:5432/customer
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db-service
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: