spring:
  application.name: hands-on-spring-boot-101
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    #    properties:
    #      hibernate:
    #        format_sql: true
    show-sql: false
server:
  port: 8080
